/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnifyingAPI */

#ifndef _Included_UnifyingAPI
#define _Included_UnifyingAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnifyingAPI
 * Method:    convert_raw_to_unified
 * Signature: ([BIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_UnifyingAPI_convert_1raw_1to_1unified
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring, jstring, jstring);

/*
 * Class:     UnifyingAPI
 * Method:    convert_unified_to_raw
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_UnifyingAPI_convert_1unified_1to_1raw
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
